# Basic Python

## 1. Split this string

In [4]:
s = "Hi there Sam!"

In [5]:
a=s.split()
print(a)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742

In [7]:
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [9]:
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [10]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [11]:
ary=np.zeros(10)
print("Array of 10 zeros:", ary)

Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
ary=np.ones(10)*5
print("Array of 10 fives:", ary)

Array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [13]:
ary=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35", ary)

Array of all the even integers from 20 to 35 [20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
a =  np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [15]:
l = np.array([1, 2, 3])
j = np.array([4, 5, 6])
k=np.concatenate((l,j))
print(k)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd


In [16]:
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df)

   Name  Age
0   tom   10
1  nick   15
2  juli   14


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
from datetime import timedelta, date

def daterange(date1, date2):
    for n in range(int ((date2 - date1).days)+1):
        yield date1 + timedelta(n)

start_dt = date(2023, 1, 1)
end_dt = date(2023, 2, 10)
for dt in daterange(start_dt, end_dt):
    print(dt.strftime("%d-%m-%Y"))
	

01-01-2023
02-01-2023
03-01-2023
04-01-2023
05-01-2023
06-01-2023
07-01-2023
08-01-2023
09-01-2023
10-01-2023
11-01-2023
12-01-2023
13-01-2023
14-01-2023
15-01-2023
16-01-2023
17-01-2023
18-01-2023
19-01-2023
20-01-2023
21-01-2023
22-01-2023
23-01-2023
24-01-2023
25-01-2023
26-01-2023
27-01-2023
28-01-2023
29-01-2023
30-01-2023
31-01-2023
01-02-2023
02-02-2023
03-02-2023
04-02-2023
05-02-2023
06-02-2023
07-02-2023
08-02-2023
09-02-2023
10-02-2023


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [18]:

  
a = pd.DataFrame(lists, columns =['Sno', 'Name', 'Num']) 
print(a)

   Sno Name  Num
0    1  aaa   22
1    2  bbb   25
2    3  ccc   24
